name: 'cache-build-artifact'
description: >-
  Caches a tarred file or directory into a short-lived artifact for use with
  later jobs.
inputs:
  path:
    description: 'Path of file or files to archive'
    required: true
    default: './'
  archive-name:
    description: 'The name of the archive'
    required: true
    default: 'build-${{ env.GITHUB_SHA }}'
runs:
  using: 'composite'
  steps:
    - name: 'Tar files 🤐'
      run: 'tar --create --file "${{ inputs.archive-name }}" "${{ inputs.path }}"'
      shell: 'bash'
    - name: 'Cache build 🧩'
      uses: 'actions/upload-artifact@v3'
      with:
        name: '${{ inputs.archive-name }}'
        path: '${{ inputs.archive-name }}'
        retention-days: 1
